# Generated by Django 3.1.4 on 2021-01-03 01:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_basicpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True)), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')], requried=True)), ('centered', wagtail.core.blocks.BooleanBlock(default=False, help_text='Check this box to center the header text.', required=False))])), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('faqs', wagtail.core.blocks.StructBlock([('show', wagtail.core.blocks.IntegerBlock(default=5, help_text='Display this many FAQs in the block.', label='Number of FAQs to Display'))]))]),
        ),
    ]
