version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: react_wagtail_app_web
    container_name: rw-web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: rw-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=react_wagtail_dev
      - POSTGRES_USER=react_wagtail
      - POSTGRES_PASSWORD=react_wagtail

volumes:
  postgres_data:
